// Next
import type { Metadata } from "next";

// Css
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

// React
import { AuthProvider } from "@/contexts/auth";

// Biblioteca
import NextTopLoader from "nextjs-toploader";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <AuthProvider>
          <NextTopLoader
            color="#ef4444"
          />
          {children}
          <ToastContainer autoClose={3000} />
        </AuthProvider>
      </body>
    </html>
  );
}
